name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: smartinvoicepro
  PYTHON_VERSION: '3.9'

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ./
            !.git/
            !.github/
            !venv/
            !__pycache__/
            !*.pyc
            !*.pyo

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Add Oryx marker to trigger Python build
        run: echo "python" > .python_packages

      - name: Set startup command for Azure
        run: |
          echo "gunicorn run:app --bind=0.0.0.0:8000" > startup.txt

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}


