name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: smartinvoicepro
  PYTHON_VERSION: '3.12'

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Remove old virtual environment if exists
        run: |
          if [ -d "antenv" ]; then rm -rf antenv; fi
          if [ -d "venv" ]; then rm -rf venv; fi

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     pip install pytest
      #     pytest


      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ./
            !venv/
            !.git/
            !.github/

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: 'Set startup command for Azure App Service'
        run: |
          echo 'python run.py' > startup.txt

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
