name: Deploy Python app to Azure Web App - smartinvoicepro

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C0641F72723F495E9B32C6E6F90C5FC8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EB5B91D8ED404A83A879138BEC548139 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_72B882493F2E474988919E2B5AD43F5D }}

      - name: Deploy raw code to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'smartinvoicepro'
          slot-name: 'Production'
          package: .
